name: development
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dotenv: ^4.2.0
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.12.0
  device_preview: ^1.3.1
  timeline_tile: ^2.0.0
  file_picker: ^10.3.10
  url_launcher: ^6.3.2
  intl: ^0.20.2
  path: ^1.9.1
  mime: ^2.0.0
  dio: ^5.9.1
  open_filex: ^4.7.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  supabase: ^2.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

